applications:
- api_domain: api.rocket.jitdev.io
  application_name: jit-rocket
  authentication_mode: non-authenticated
  exclude_paths: []
  target_url: https://platform.rocket.jitdev.io
  type: web

